apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroku
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroku
  template:
    metadata:
      labels:
        app: heroku
    spec:
      containers:
        - name: heroku
          image: dulcinee/heroku
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: herokou-service
  namespace: jenkins
spec:
  selector:
    app: heroku
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
